package frc.team3128.common.hardware.motorcontroller;

import com.ctre.phoenix.ErrorCode;
import com.ctre.phoenix.motorcontrol.ControlMode;
import com.ctre.phoenix.motorcontrol.DemandType;
import com.ctre.phoenix.motorcontrol.TalonFXSimCollection;
import com.ctre.phoenix.motorcontrol.can.WPI_TalonFX;

import edu.wpi.first.wpilibj.RobotBase;

public class NAR_TalonFX extends WPI_TalonFX {

	private double prevValue = 0;
	private ControlMode prevControlMode = ControlMode.Disabled;
	private DemandType prevDemandType = DemandType.Neutral;
	private double prevDemand = 0;

	private TalonFXSimCollection motorSim;

	/**	 
	 * @param deviceNumber device id
	 */
	public NAR_TalonFX(int deviceNumber, String canBus) {
		super(deviceNumber, canBus);

		if(RobotBase.isSimulation()){
			motorSim = getTalonFXSimCollection();
		}

		configVoltageCompSaturation(12, 10);
		enableVoltageCompensation(true);
	}

	public NAR_TalonFX(int deviceNumber) {
		this(deviceNumber, "");
	}

	@Override
	public void set(double speed) {
		set(speed, ControlMode.PercentOutput);
	}

	public void set(double outputValue, ControlMode controlMode) {
		set(controlMode, outputValue, DemandType.Neutral, 0);
	}

	public void set(double outputValue, ControlMode controlMode, double demand) {
		set(controlMode, outputValue, DemandType.ArbitraryFeedForward, demand);
	}

	public void set(double outputValue, ControlMode controlMode, DemandType demandType, double demand) {
		if (controlMode == ControlMode.Position) {
			outputValue *= MotorControllerConstants.FALCON_ENCODER_RESOLUTION;
		}
		if (controlMode == ControlMode.Velocity) {
			outputValue *= MotorControllerConstants.RPM_TO_FALCON;
		}
		if (outputValue != prevValue || controlMode != prevControlMode || demandType != prevDemandType || demand != prevDemand) {
			super.set(controlMode, outputValue, demandType, demand);
			prevValue = outputValue;
			prevControlMode = controlMode;
			prevDemandType = demandType;
			prevDemand = demand;
		}
	}

	// getInverted() stuff should only be temporary
	public void setSimPosition(double pos) {
		if(super.getInverted()) {
			pos *= -1;
		}
		motorSim.setIntegratedSensorRawPosition((int)pos);
	}

	// getInverted() stuff should only be temporary
	public void setSimVelocity(double vel) {
		if(super.getInverted()) {
			vel *= -1;
		}
		motorSim.setIntegratedSensorVelocity((int)(vel/10)); // convert nu/s to nu/100ms
	}

	/**
	 * Sets the sensor position to the given value.
	 *
	 * @param sensorPos
	 *            Position to set for the selected sensor (in rotations).
	 * @return Error Code generated by function. 0 indicates no error.
	 */
	@Override
	public ErrorCode setSelectedSensorPosition(double sensorPos) {
		return super.setSelectedSensorPosition(sensorPos * MotorControllerConstants.FALCON_ENCODER_RESOLUTION); //Rotations to nu
	}

	/**
	 * Get the selected sensor velocity.
	 *
	 * @return sensor velocity in rotations per minute (RPM)
	 */
	@Override
	public double getSelectedSensorVelocity() {
		return super.getSelectedSensorVelocity() * 600 / MotorControllerConstants.FALCON_ENCODER_RESOLUTION; // convert nu/100ms to rpm
	}

	/**
	 * Get the selected sensor position
	 *
	 * @return Position of selected sensor (in rotations).
	 */
	@Override
	public double getSelectedSensorPosition() {
		return super.getSelectedSensorPosition() / MotorControllerConstants.FALCON_ENCODER_RESOLUTION; // convert nu to rotations
	}
}